[server]
# Reduce file watching to prevent inotify limit issues
fileWatcherType = "none"

[runner]
# Disable fast reruns to reduce file watching
fastReruns = false

[logger]
# Reduce logging verbosity
level = "error"

[theme]
base = "light"
primaryColor = "#4CAF50"              # vibrant green
backgroundColor = "#F1F8E9"           # light green tint
secondaryBackgroundColor = "#E8F5E8"  # soft green
textColor = "#1B5E20"                 # dark green
font = "sans serif"