[server]
# Reduce file watching to prevent inotify limit issues
fileWatcherType = "none"

[runner]
# Disable fast reruns to reduce file watching
fastReruns = false

[logger]
# Reduce logging verbosity
level = "error"